title: 'Odvjetničko društvo Čerin, Mar i partneri'
default_lang: hr
author:
  name: 'Tihana Ana Reljić'
  email: antonijapek@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
